print("Welcome to the Interactive Personal Data Collector!")

name = input("Please enter a name: ")
age = int(input("Please enter your age: "))
height = float(input("Please enter your height (in meters): "))
favnumber = int(input("Please enter your favorite number: "))

print()
print("\nThank you for providing your information!")
print()
print(f"Name: {name}(type: {type(name)}, memory address: {id(name)})")
print(f"Age: {age}(type: {type(age)}, memory address: {id(age)})")
print(f"Height: {height}(type: {type(height)}, memory address: {id(height)})")
print(f"Favorite Number: {favnumber}(type: {type(favnumber)}, memory address: {id(favnumber)})")
print()
print(f"Your birth year is {2026 - age} based on your age of {age}.")
print()
print(f"Thank you for using the Interactive Personal Data Collector! Have a great day!")
print()